spring:
  profiles:
    active: local
  application:
    name: demo

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${ACCESS_TOKEN_EXPIRATION} #a day
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION} # 7 days
api-version:
  prefix: /api/v1
